# Symmetry check
Idea: Check with spglib the combined symmetries

# $MnI_2$

In [1]:
from magnetic_symmetry_analysis import analyse_magnetic_symmetry
from spinspiral import construct_full
import numpy as np

In [5]:
# ─────────────────────────────────────────────────────────────────────────────
# Build supercell
# ─────────────────────────────────────────────────────────────────────────────

theta_mni2, phi_mni2 = 0, 0
path_to_cif_mni2 = "1MnI2-1.cif"
Q_mni2 = [1/3, 1/3, 0]
magnetic_magnitude_mni2 = 4.5

P_mni2 = np.array([
    [2,  1, 0],
    [-1, 1, 0],
    [0,  0, 1]
])

supercell_mni2, name_mni2 = construct_full(
    theta=theta_mni2, phi=phi_mni2, Q=Q_mni2,
    path=path_to_cif_mni2, transform=P_mni2,
    magnitude=magnetic_magnitude_mni2,
    magsymbols='Mn',
    init_moment=[0, magnetic_magnitude_mni2, 0]
)

# ─────────────────────────────────────────────────────────────────────────────
# Run analysis
# ─────────────────────────────────────────────────────────────────────────────

# analyse_magnetic_symmetry(supercell, save_txt=True)
analyse_magnetic_symmetry(supercell_mni2, theta=theta_mni2, phi=phi_mni2, save_txt=False)

n_hat = [0. 0. 1.]
Initial moment= [0.  4.5 0. ]
Cell information
Lattice (Å):
 [[ 6.24857382  3.60761578  0.        ]
 [-6.24857382  3.60761578  0.        ]
 [ 0.          0.         18.02743121]]

Fractional positions:
 [[4.77726582e-19 9.57147230e-19 5.00000000e-01]
 [3.33333333e-01 1.23097701e-16 5.91501375e-01]
 [3.33333333e-01 3.33333333e-01 4.08498625e-01]
 [3.33333333e-01 6.66666667e-01 5.00000000e-01]
 [6.66666667e-01 6.66666667e-01 5.91501375e-01]
 [6.66666667e-01 1.00000000e+00 4.08498625e-01]
 [6.66666667e-01 3.33333333e-01 5.00000000e-01]
 [1.00000000e+00 3.33333333e-01 5.91501375e-01]
 [1.00000000e+00 6.66666667e-01 4.08498625e-01]]

Atomic numbers: [25 53 53 25 53 53 25 53 53]

Magnetic moments (cleaned):
 [[ 0.          4.5         0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 3.89711432 -2.25        0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [-3.89711432 -2.25        0.      

# $MnTe_2$

In [6]:
theta_mnte2, phi_mnte2 = 0,0

path_to_cif_mnte2 = "1MnTe2-2.cif"

Q_mnte2 = [1/3,1/3,0]

magnetic_magnitude_mnte2 = 2.8 #Start value based on https://c2db.fysik.dtu.dk/material/1MnTe2-2

init_moment_mnte2=[0,magnetic_magnitude_mnte2,0]

#Define transformation matrix from primitive to magnetic cell
P_mnte2 = np.array([
    [2, 1, 0],
    [-1, 1, 0],
    [0, 0, 1]
])

magnetic_atom_mnte2 = 'Mn'

supercell_mnte2 , name_mnte2 = construct_full(theta = theta_mnte2, phi=phi_mnte2, Q=Q_mnte2 , path= path_to_cif_mnte2, transform=P_mnte2, magnitude=magnetic_magnitude_mnte2, magsymbols=magnetic_atom_mnte2, init_moment=init_moment_mnte2)


analyse_magnetic_symmetry(supercell_mnte2,theta=theta_mnte2, phi=phi_mnte2, save_txt=False)

n_hat = [0. 0. 1.]
Initial moment= [0.  2.8 0. ]
Cell information
Lattice (Å):
 [[ 5.49009749  3.16970926  0.        ]
 [-5.49009749  3.16970926  0.        ]
 [ 0.          0.         18.22538261]]

Fractional positions:
 [[0.00000000e+00 0.00000000e+00 5.00000002e-01]
 [3.33333333e-01 3.50260208e-17 5.90235992e-01]
 [3.33333333e-01 3.50260208e-17 4.09764020e-01]
 [3.33333333e-01 6.66666667e-01 5.00000002e-01]
 [6.66666667e-01 6.66666667e-01 5.90235992e-01]
 [6.66666667e-01 6.66666667e-01 4.09764020e-01]
 [6.66666667e-01 3.33333333e-01 5.00000002e-01]
 [3.23556520e-16 3.33333333e-01 5.90235992e-01]
 [3.23556520e-16 3.33333333e-01 4.09764020e-01]]

Atomic numbers: [25 52 52 25 52 52 25 52 52]

Magnetic moments (cleaned):
 [[ 0.          2.8         0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 2.42487113 -1.4         0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [-2.42487113 -1.4         0.      

# $\mathrm{VAl_2Se_4}$

In [7]:
#Normal vector orientation in spherical
theta_V, phi_V = 90,0

path_to_cif_V = "1VAl2Se4-1.cif"

Q_V = [-1/3,-1/3,0]

magnetic_magnitude_V = 2.3

#Define transformation matrix from primitive to magnetic cell
P_V = np.array([
    [2, 1, 0],
   [-1, 1, 0],
    [0, 0, 1]
])

magnetic_atom_V = 'V'

supercell_V , name_V = construct_full(theta = theta_V, phi=phi_V, Q=Q_V , path= path_to_cif_V, transform=P_V, magnitude=magnetic_magnitude_V, magsymbols=magnetic_atom_V)


n_hat = [1.000000e+00 0.000000e+00 6.123234e-17]
Initial moment= [0.  2.3 0. ]


In [9]:
analyse_magnetic_symmetry(supercell_V,theta=theta_V, phi=phi_V, save_txt=False)

Cell information
Lattice (Å):
 [[ 5.84647527  3.37546407  0.        ]
 [-5.84647527  3.37546407  0.        ]
 [ 0.          0.         39.45524608]]

Fractional positions:
 [[1.46773869e-17 1.46773869e-17 5.00000000e-01]
 [3.33333333e-01 4.93364617e-16 4.07169622e-01]
 [3.33333333e-01 3.33333333e-01 5.92830378e-01]
 [3.33333333e-01 4.93364617e-16 4.66597128e-01]
 [3.33333333e-01 3.33333333e-01 5.33402872e-01]
 [3.33333333e-01 4.93364617e-16 6.19986754e-01]
 [3.33333333e-01 3.33333333e-01 3.80013246e-01]
 [3.33333333e-01 6.66666667e-01 5.00000000e-01]
 [6.66666667e-01 6.66666667e-01 4.07169622e-01]
 [6.66666667e-01 3.28909745e-16 5.92830378e-01]
 [6.66666667e-01 6.66666667e-01 4.66597128e-01]
 [6.66666667e-01 3.28909745e-16 5.33402872e-01]
 [6.66666667e-01 6.66666667e-01 6.19986754e-01]
 [6.66666667e-01 3.28909745e-16 3.80013246e-01]
 [6.66666667e-01 3.33333333e-01 5.00000000e-01]
 [9.49480648e-16 3.33333333e-01 4.07169622e-01]
 [1.51916904e-16 6.66666667e-01 5.92830378e-01]
 [9.4948064

Forstår ikke helt hvorfor der er så få symmetrier for denne, men odd-parity er bevaret...

Ah, det er fordi SOC er utroligt svag. Den er ikke tvunget til bevaret, SOC er bare for lille.

Den ene symmetri der er tilstede med SOC er $C2[1,-1,0]+TR$ som effektivt set gør følgende på spins:
$ (s_x,s_y,s_z) \rightarrow (s_y,s_x,s_z) $ (swap x og y)

og følgende på space:
$ (x,y,z) \rightarrow (-y,-x,-z)  $

Det er lidt svært at se hvilke sites der bliver mapped til hvilke, og hvorfor det derfor er en symmetri.